name: repoviewer
description: Simple flutter application with github oauth feature.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  oauth2: ^2.0.1
  dartz: ^0.10.1
  dio: ^4.0.6
  ionicons: ^0.2.1
  flutter_secure_storage: ^4.2.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  json_annotation: ^4.7.0
  webview_flutter: ^3.0.4
  flash: ^2.0.5
  google_fonts: ^3.0.1
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint: ^2.0.1
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
